export default function Head() {
  return (
    <>
      <title>Online letter</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link precedence="default" rel="preconnect" href="https://fonts.googleapis.com"/>
      <link precedence="default" rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
      <link precedence="default" href="https://fonts.googleapis.com/css2?family=Passion+One&display=swap" rel="stylesheet"></link>
      <link precedence="default"  href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"></link>
      <link precedence="default" href="https://fonts.googleapis.com/css2?family=Signika&display=swap" rel="stylesheet"></link>
    </>
  )
}
